sudo: required
dist: bionic
language: python
python:
  - '3.6'

before_install:
  - pip install -U pip awscli

install:
  - bash scripts/build.sh

script:
  - test -d dist/  # ensure dist/ exists, meaning site was built

before_deploy:
  - aws configure set region $AWS_REGION
  - aws configure set preview.cloudfront true

deploy:
  # deploy release to s3 bucket
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: "$S3_BUCKET"
    local_dir: "dist"
    skip_cleanup: true
    upload-dir: "$S3_PREFIX"
    region: "$AWS_REGION"
    on:
      branch: release

after_deploy:
  - /bin/bash scripts/cloudfront-invalidate.sh
